spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/service
    username: batchuser
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: true
      host: localhost
      port: 6379 # default
